GET http://localhost:3000/users

###
GET http://localhost:3000/

###

POST http://localhost:3000/register
Content-Type: application/json

{
    "email" : "liu@julien.fr",
    "password" : "ouioui",
    "firstName" : "Julien",
    "lastName" : "Liu",
    "phoneNumber" : "5432109876"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "liu@julien.fr",
    "password" : "ouioui"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "Caca@pipi.fr",
    "password" : "NTM"
}